### ISSUE TITLE
Choosing Color Scheme For Web Application

### ISSUE THREAD

**Issue by Rubix982** [Rubix982/Reflex#10]
The application needs a color scheme. One suggestion is the below from `coolors.com`.

![image](https://user-images.githubusercontent.com/41635766/117116034-4abd5d80-ada7-11eb-9d89-223cd75ea7a3.png)

The coolors generator can be seen [here](https://coolors.co/264653-2a9d8f-e9c46a-f4a261-e76f51).

**Comment by Rubix982** [comment]
Current hex values,

- 101E23, Rich Black FOGRA 29
- 122126, Charleston Green
- 14242A, Charleston Green
- 182C33, Gunmetal
- 23404B, Charcoal
- 2A9D8F, Persian, Green
- E9C46A, Orange Yellow Crayola
- EFB366, Sunray
- EFB366, Sandy Brown
- E76F51, Burnt Sienna

**Comment by areej-sultana1** [comment]
The color scheme would go well with our system as it has quite a good variety.

**Comment by Rubix982** [comment]
Great, @areej-sultana1 . I'm making the UI models with Figma right now. You can see them [here](https://www.figma.com/file/PKzIocgkOTkDdy2mtKyk9c/Reflex?node-id=0%3A1)

**Comment by areej-sultana1** [comment]
okay, I'll keep checking that.

**Comment by Rubix982** [comment]
Closing.
