### ISSUE TITLE
[CLIENT] Teacher Dashboard Page 

### ISSUE THREAD

**Issue by Rubix982** [Rubix982/Reflex#5]
Currently, the chosen ReactJS template for creating the teacher dashboard page looks like the following,

![image](https://user-images.githubusercontent.com/41635766/116193111-48745700-a748-11eb-9acf-7ae71b026cfb.png)

The demo of this page can be seen [here](https://demos.creative-tim.com/material-dashboard-react/?&_ga=2.212756247.226476551.1619454786-557660508.1616210029#/admin/dashboard)

Clearly, it needs a lot of changes to change to the user requirements, thus, it makes sense to allow options for future use case desires and requirements.

At the moment, there are ideas about what to add and what to remove. Client meeting would seem like a good option to discuss what can be added and removed, and what should remain for the core 'Attendance' use case functionality.

**Comment by Rubix982** [comment]
@areej-sultana1, can you take a lot at this and provide a recommendation? Thank you.

**Comment by areej-sultana1** [comment]
Template dashboard looks completely fine as it can be customized according to the use cases of attendance system.

**Comment by Rubix982** [comment]
Alright. (Y) 

We should move this to Figma move to see how this integrates with our existing UI

**Comment by Rubix982** [comment]
Closed in favor of #9
